version: '3.8'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: 1590
      MYSQL_TCP_PORT: 3306
    cap_add:
      - ALL
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "9000:80"
    environment:
      PMA_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1590
      MYSQL_ROOT_PASSWORD: password